---
- hosts: 172.31.84.243
  become: yes
  tasks:
  - name: to excute linux commands
    command: hostname -f
    register: myfirsttaskresult

  - name: want to see first task result
    debug:
     mgs: "{{myfirsttaskresult}}"
  