---
- hosts: 172.31.84.243
  become: yes
  tasks:
  - name: to excute linux commands
    command: hostname -f
    register: myfirsttaskresult

  - name: want to see first task result
    debug:
     msg: "{{myfirsttaskresult}}"

  - name: install git
    apt:
      name: git
      state: present
    when: myfirsttaskresult.stderr ==""

  - name: install tree
    apt:
      name: tree
      state: present
    when: myfirsttaskresult.stderr !=""

  