---
- hosts: 172.31.84.243
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: i want to copy ansible master to node
    copy:
     src: mystatic
     dest: /home/ubuntu/mystaticfile


  - name: i want to install webserver
    apt:
      name: apache2
      state: present

  - name : want to copy dynamic to node
    template:
       src: myindexfile.j2
       dest: /var/www/html/index.html