---
- hosts: all
  become: yes
  tasks:
  - name:  i want to install webserver on ubutu
    apt:
     name: "{{mywebpackonubutun}}"
     state: present
    when: ansible_os_family == "Debian"

  - name: i want to install webserver on Redhat
    yum:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family == "RedHat"
  
